### ISSUE TITLE
Can't install v9 since v10 was released

### ISSUE THREAD

**Issue by kevinjbayer** [directus/create-directus-project#10]
When I try to use `npm init directus-project`, it fails with the following:

```
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: directus@10.0.0
npm ERR! notsup Not compatible with your version of node/npm: directus@10.0.0
npm ERR! notsup Required: {"node":">=18.0.0"}
npm ERR! notsup Actual:   {"npm":"8.11.0","node":"v16.15.1"}
```

I've attempted it also on a setup where 2 or 3 weeks ago it worked fine. Changed nothing except removed the old project folder and re-ran it. There's no reference to directus 10.0.0 in package.json, and I can't figure out why it's attempting to load it. I know this code hasn't been updated in a while, but is there something in here that is automatically fetching the latest version no matter what?

Also, I'm upgrading a v8 to v9 currently, so I'm only trying to install v9.2.1 to incrementally get up to the latest 9. I had it working great on a staging server, until I hit this snag since v10 came out.

**Comment by rijkvanzanten** [comment]
Directus requires Node active LTS, which at time of writing is v18. You're using v16, which is incompatible 👍🏻

**Comment by kevinjbayer** [comment]
@rijkvanzanten Thanks for responding. Why did it work 3 weeks ago before v10 was released? Even v9 requires Node v18?

**Comment by rijkvanzanten** [comment]
> Why did it work 3 weeks ago before v10 was released? Even v9 requires Node v18?

Probably because whatever older version you were using wasn't using Node 18 APIs yet, whereas later versions did. Regardless, Directus has always required active Node LTS, which includes v9
