### ISSUE TITLE
Mysql version

### ISSUE THREAD

**Issue by Mayanktaker** [directus/create-directus-project#11]
Getting error of mysql version because its not supported.
Please change it to mysql2 (3.3.5) latest version.

**Comment by rijkvanzanten** [comment]
This sounds like a bug in Directus itself (not this installer wrapper), but there's not nearly enough information to reproduce or debug anything. Please open an issue on [`directus/directus`](https://github.com/directus/directus/issues/new) and make sure to include what the error is, and what steps you took to see the error 👍🏻
