### ISSUE TITLE
Install via npm failed (Win/MacOS/Linux)

### ISSUE THREAD

**Issue by kuzmi4** [directus/create-directus-project#2]
### Describe the Bug

I tried make fresh instalation of directus via **npm**  on 3 platforms, but recieved errors  with @napi-rs/snappy*:

**Windows:**
![image](https://user-images.githubusercontent.com/6544815/183260141-5840fcb9-38c3-4499-aa2d-7da057db6aee.png)
**Linux**: 
![image](https://user-images.githubusercontent.com/6544815/183260174-0ae7503a-0014-4e7b-a5f8-e4153b799a8d.png)
**MacOS**
![photo_2022-08-06_20-50-19](https://user-images.githubusercontent.com/6544815/183260258-0db63436-4355-47f9-91e9-611e7e23feaa.jpg)

### To Reproduce

Just use: `npm init directus-project example-project
`

### What version of Directus are you using?

9.15.1

### What version of Node.js are you using?

16

### What database are you using?

 SQLite

### What browser are you using?

Edge

### How are you deploying Directus?

npm

**Comment by tomkenkel** [comment]
Still getting this snappy error. To clarify for people like me, use both of these in your new Directus directory:
`npm install directus` and `npx directus init`
